CREATE TABLE user_info
(
    ID BIGSERIAL PRIMARY KEY,
    ROLE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE expense
(
    ID BIGSERIAL PRIMARY KEY,
    AMOUNT NUMERIC NOT NULL DEFAULT 0,
    CATEGORY VARCHAR(255) NOT NULL DEFAULT 'General',
    DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES user_info(ID)
);